name: Continuous Integration
on: [push]

jobs:
  ci:
    steps:
      - uses: actions/checkout@v4
      - uses: msrd0/rust-toolchain@nightly
      - run: |
          cd kernel
          cp config.aphro.example config.aphro
          ./build
          mkdir release
          mv aphrodite-*.iso release
      - name: Publish Release
        uses: actions/forgejo-release@v2
        with:
          direction: upload
          url: https://git.verygay.fyi
          release-dir: kernel/release
          release-notes: "Continuous Integration"
      