unstable_features = true
binop_separator = "Back"
wrap_comments = true
edition = "2024"
style_edition = "2024"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
match_block_trailing_comma = true
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
trailing_comma = "Vertical"
trailing_semicolon = true
use_try_shorthand = true