[package]
name = "aphrodite_proc_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true
path = "../src/proc_macros/mod.rs"

[dependencies]
quote = "1.0.38"
syn = { version = "2.0.98", features = ["full"] }
aphrodite_common = { path = "../aphrodite_common" }
proc-macro2 = "1.0.93"
